import {
  createGame,
  drawCards,
  isHighImpactSpecialKind,
  isImmediateInteractionKind,
  type Card,
  type GameState,
} from '../../../packages/game-engine/src/index.ts';

function newSeed(): string {
  if (globalThis.crypto?.randomUUID) return globalThis.crypto.randomUUID();
  const bytes = new Uint32Array(4);
  globalThis.crypto?.getRandomValues?.(bytes);
  return `pulse-${Date.now()}-${Array.from(bytes).join('-')}`;
}

function escapeHtml(value: unknown): string {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function familyLabel(card: Card): string {
  return card.kind
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function cardClass(card: Card): string {
  if (isImmediateInteractionKind(card.kind)) return 'is-interaction';
  if (isHighImpactSpecialKind(card.kind)) return 'is-special';
  if (card.kind === 'skip' || card.kind === 'reverse' || card.kind === 'draw') return 'is-action';
  return 'is-number';
}

function cardPill(card: Card): string {
  const suffix = card.kind === 'number' ? ` ${card.value ?? ''}` : '';
  return `<span class="chaos-pulse-lab__card ${cardClass(card)}">${escapeHtml(familyLabel(card))}${escapeHtml(suffix)}</span>`;
}

function createLabGame(playerCount: number): GameState {
  const players = Array.from({ length: playerCount }, (_, index) => ({ id: `lab-player-${index + 1}` }));
  const result = createGame({ seed: newSeed() }, players);
  if (!result.ok) throw result.error ?? new Error('CHAOS Pulse game creation failed.');
  return result.state;
}

function renderHands(state: GameState): string {
  return state.players.map((player, index) => {
    const specialCount = player.hand.filter(card => isHighImpactSpecialKind(card.kind)).length;
    const interactionCount = player.hand.filter(card => isImmediateInteractionKind(card.kind)).length;
    return `
      <article class="chaos-pulse-lab__hand">
        <header>
          <strong>Player ${index + 1}</strong>
          <span>${specialCount} special${specialCount === 1 ? '' : 's'} · ${interactionCount} interaction</span>
        </header>
        <div class="chaos-pulse-lab__cards">${player.hand.map(cardPill).join('')}</div>
      </article>
    `;
  }).join('');
}

function renderDraws(state: GameState, count = 12): string {
  const rows: string[] = [];
  for (let index = 0; index < count && state.drawPile.length; index += 1) {
    const pressureBefore = state.adaptiveProbability?.interactionPressure ?? 1;
    const [card] = drawCards(state, 1);
    if (!card) break;
    const pressureAfter = state.adaptiveProbability?.interactionPressure ?? pressureBefore;
    rows.push(`
      <div class="chaos-pulse-lab__draw-row">
        <span class="chaos-pulse-lab__draw-index">${index + 1}</span>
        ${cardPill(card)}
        <span class="chaos-pulse-lab__pressure">pressure ${pressureBefore.toFixed(2)} → ${pressureAfter.toFixed(2)}</span>
      </div>
    `);
  }
  return rows.join('');
}

function renderTrial(host: HTMLElement, playerCount: number): void {
  const state = createLabGame(playerCount);
  const seed = state.config.seed;
  const openingMarkup = renderHands(state);
  const drawMarkup = renderDraws(state, 12);

  host.innerHTML = `
    <div class="chaos-pulse-lab__summary">
      <div><span>Seed</span><strong>${escapeHtml(seed)}</strong></div>
      <div><span>Players</span><strong>${playerCount}</strong></div>
      <div><span>Opening rule</span><strong>1–2 specials each</strong></div>
      <div><span>Deck authority</span><strong>CHAOS-133-V1</strong></div>
    </div>

    <section>
      <h3>Opening hands</h3>
      <p class="chaos-pulse-lab__hint">These are generated by the real shared adaptive dealer. Interaction cards shown here stay playable later because they came from the opening deal.</p>
      <div class="chaos-pulse-lab__hands">${openingMarkup}</div>
    </section>

    <section>
      <h3>Next 12 adaptive physical draws</h3>
      <p class="chaos-pulse-lab__hint">Each row recalculates availability, freshness, interaction pressure, primary CHAOS, rebalancing, and final jitter before selecting the next real card.</p>
      <div class="chaos-pulse-lab__draws">${drawMarkup}</div>
    </section>
  `;
}

export function mountChaosPulseLab(): void {
  const actions = document.querySelector<HTMLElement>('.cc-web-actions');
  if (!actions || document.querySelector('#chaosPulseLabButton')) return;

  const openButton = document.createElement('button');
  openButton.id = 'chaosPulseLabButton';
  openButton.type = 'button';
  openButton.className = 'button chaos-pulse-lab__open';
  openButton.textContent = 'Try CHAOS Pulse';
  openButton.title = 'Open the live adaptive distribution trial';
  actions.append(openButton);

  const dialog = document.createElement('dialog');
  dialog.id = 'chaosPulseLab';
  dialog.className = 'chaos-pulse-lab';
  dialog.innerHTML = `
    <div class="chaos-pulse-lab__shell">
      <header class="chaos-pulse-lab__header">
        <div>
          <span class="chaos-pulse-lab__eyebrow">LIVE SHARED-ENGINE TRIAL</span>
          <h2>CHAOS Pulse</h2>
          <p>Adaptive Weights → Primary CHAOS → Rebalancer → Secondary CHAOS → Safety Guard</p>
        </div>
        <button type="button" class="chaos-pulse-lab__close" aria-label="Close CHAOS Pulse trial">×</button>
      </header>

      <div class="chaos-pulse-lab__controls">
        <label>
          Players
          <input class="chaos-pulse-lab__players" type="number" min="2" max="10" step="1" value="5">
        </label>
        <button type="button" class="button chaos-pulse-lab__reroll">New random match</button>
      </div>

      <div class="chaos-pulse-lab__notice">
        This trial calls the canonical shared game engine directly. The current main board still uses the legacy compatibility runtime until its deck seam is migrated, so use this panel to judge the new distribution itself.
      </div>

      <main class="chaos-pulse-lab__content"></main>
    </div>
  `;
  document.body.append(dialog);

  const content = dialog.querySelector<HTMLElement>('.chaos-pulse-lab__content');
  const playerInput = dialog.querySelector<HTMLInputElement>('.chaos-pulse-lab__players');
  const reroll = dialog.querySelector<HTMLButtonElement>('.chaos-pulse-lab__reroll');
  const close = dialog.querySelector<HTMLButtonElement>('.chaos-pulse-lab__close');

  const run = (): void => {
    if (!content || !playerInput) return;
    const playerCount = Math.min(10, Math.max(2, Math.round(Number(playerInput.value) || 5)));
    playerInput.value = String(playerCount);
    try {
      renderTrial(content, playerCount);
    } catch (error) {
      content.innerHTML = `<p class="chaos-pulse-lab__error">${escapeHtml(error instanceof Error ? error.message : error)}</p>`;
    }
  };

  openButton.addEventListener('click', () => {
    run();
    dialog.showModal();
  });
  reroll?.addEventListener('click', run);
  playerInput?.addEventListener('change', run);
  close?.addEventListener('click', () => dialog.close());
  dialog.addEventListener('click', event => {
    if (event.target === dialog) dialog.close();
  });
}
