import type { Card, CardColor, GameCommand, GameState, MachiavelliEffectId } from '../../../packages/contracts/src/index.ts';
import { ApiError, CribbitApiClient, CribbitRealtimeClient, type RoomSessionResult } from '../../../packages/api-client/src/index.ts';
import { isLegalPlay } from '../../../packages/game-engine/src/index.ts';
import { cribbitAuth } from '../../../packages/ui/src/auth-controller.ts';
import { openWebAuthDialog } from './web-auth.ts';

type LivePlayer={id:string;name:string;isHuman:boolean};
type CommandBody<T=GameCommand>=T extends GameCommand?Omit<T,'commandId'|'playerId'|'expectedRevision'|'sessionId'>:never;
type LiveSession={room:RoomSessionResult;state:GameState;players:LivePlayer[];realtime:CribbitRealtimeClient;unsubscribe?:()=>void;status?:string};
const MACHIAVELLI:readonly [MachiavelliEffectId,string][]=[['CONVERT_WEAK','Convert Weak'],['TABOO_ALL','Taboo for All'],['NO_MERCY','No Mercy'],['PARANOIA_SPREADS','Paranoia Spreads'],['DOUBLE_PRESSURE','Double Pressure'],['REVERSE_CONFESSION_ALL','Reverse Confession All']];

function escapeHTML(value:unknown):string{return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[char]||char);}
function titleForCard(card:Card):string{if(card.kind==='number')return`${card.color??''} ${card.value??''}`.trim();return titleForKind(card.kind);}
function titleForKind(kind:string):string{return kind.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());}
function iconForCard(card:Card):string{if(card.kind==='truth')return'i-truth';if(card.kind==='dare')return'i-lightning';if(card.kind==='paranoia')return'i-paranoia';if(card.kind==='chaos')return'i-spiral';if(card.kind==='duel')return'i-swords';if(card.kind==='nope')return'i-hand';if(card.kind==='reverse')return'i-reverse';if(card.kind==='draw')return'i-draw';if(card.kind==='skip')return'i-skip';return'i-card';}
function renderCard(card:Card,interactive:boolean,legal:boolean):string{const kind=escapeHTML(card.kind),color=card.color?` data-color="${escapeHTML(card.color)}"`:'',number=card.kind==='number'?`<span class="game-card__icon is-number">${escapeHTML(card.value)}</span>`:`<svg class="game-card__icon icon" aria-hidden="true"><use href="#${iconForCard(card)}"></use></svg>`,action=interactive?` data-action="play-card" data-card-id="${escapeHTML(card.id)}" aria-disabled="${String(!legal)}"`:'',element=interactive?'button':'div';return`<${element} class="game-card game-card--mini" data-kind="${kind}"${color}${action} data-legal="${String(legal)}" ${interactive?'type="button"':''} aria-label="${escapeHTML(titleForCard(card))}"><span class="game-card__tab"><svg class="icon" aria-hidden="true"><use href="#${iconForCard(card)}"></use></svg></span><strong class="game-card__title">${escapeHTML(titleForCard(card))}</strong>${number}<p class="game-card__rule">Shared live session</p><svg class="frog-seal icon" aria-hidden="true"><use href="#i-frog"></use></svg></${element}>`;}
function showGameView():void{document.querySelectorAll<HTMLElement>('.view').forEach(view=>view.classList.toggle('is-active',view.dataset.view==='game'));document.body.classList.add('is-game-view');window.scrollTo(0,0);}
function playerName(session:LiveSession,id:string|null|undefined):string{return session.players.find(player=>player.id===id)?.name||id||'—';}
function button(label:string,action:string,extra=''):string{return`<button class="button button--sm" type="button" data-live-action="${action}" ${extra}>${escapeHTML(label)}</button>`;}
function input(id:string,label:string,placeholder='',extra=''):string{return`<div class="field"><label for="${id}">${escapeHTML(label)}</label><input class="input" id="${id}" maxlength="280" placeholder="${escapeHTML(placeholder)}" ${extra}/></div>`;}
function textarea(id:string,label:string,placeholder=''):string{return`<div class="field"><label for="${id}">${escapeHTML(label)}</label><textarea class="input" id="${id}" maxlength="280" rows="3" placeholder="${escapeHTML(placeholder)}"></textarea></div>`;}
function targetButtons(session:LiveSession,ids:readonly string[],action:string):string{return`<div class="filter-row">${ids.map(id=>button(playerName(session,id),action,`data-player-id="${escapeHTML(id)}"`)).join('')}</div>`;}
function promptBox(label:string,text:string):string{return`<div class="authority-box"><b>${escapeHTML(label)}</b><p>${escapeHTML(text)}</p></div>`;}

function activeStateCopy(session:LiveSession):{title:string;copy:string}{const state=session.state;if(state.pendingEffect?.type==='WILD_COLOR')return{title:'Choose a color',copy:'Wild is waiting for the active player to choose the next color.'};const social=state.social;if(!social)return{title:'Play or draw',copy:'Use a legal card or draw. Railway owns the turn and all effects.'};const step=social.canonicalStep?.replaceAll('_',' ').toLowerCase();return{title:`${titleForKind(social.cardKind)}${step?` · ${step}`:''}`,copy:social.prompt?.text||social.question||social.groupDare||'Complete the active authoritative flow.'};}

function socialControls(session:LiveSession,userId:string):string{
  const state=session.state,human=state.players.find(p=>p.id===userId);
  if(state.pendingEffect?.type==='WILD_COLOR'&&state.pendingEffect.playerId===userId)return`<div class="filter-row">${(['lime','orange','cyan','purple'] as CardColor[]).map(color=>button(color.toUpperCase(),'wild-color',`data-color="${color}"`)).join('')}</div>`;
  const social=state.social;
  if(!social){
    if(state.currentPlayerId===userId&&human?.ghostArmedCard&&(human.ghostTurnsRemaining??0)===0)return button('Activate Ghost','ghost-activate');
    if(state.currentPlayerId===userId&&(human?.ghostTurnsRemaining??0)>0&&!human?.hand.some(card=>isLegalPlay(state,userId,card.id)))return button('End Ghost Turn','ghost-end');
    return'';
  }
  const step=social.canonicalStep;
  if(!step){return'<span class="tag" data-tone="cyan">Compatibility interaction in progress</span>';}
  if(step==='PROMPT_SOURCE'&&social.actorId===userId)return`${button('Write My Own','prompt-manual')} ${button('Roulette','prompt-roulette')}`;
  if(step==='MANUAL_PROMPT'&&social.actorId===userId)return`${textarea('ccManualPrompt','Your question / dare','Write the prompt here')}${button('Use This Prompt','manual-submit')}`;
  if(step==='PRIVATE_PREVIEW'&&social.actorId===userId)return`${social.prompt?promptBox('PRIVATE PREVIEW',social.prompt.text):''}${button('Use This Question','prompt-publish')}`;
  if(step==='TARGET'&&social.actorId===userId){const action=social.cardKind==='dare'?'dare-target':social.cardKind==='paranoia'?'paranoia-target':social.cardKind==='duel'?'duel-target':social.cardKind==='tag'?'tag-target':social.cardKind==='hijack'?'hijack-target':social.cardKind==='taboo'?'taboo-target':social.cardKind==='reverse_confession'?'reverse-target':social.cardKind==='dig_me'?'dig-target':'';return action?targetButtons(session,social.pendingTargetIds,action):'';}
  if(step==='ANSWER'){
    const responder=social.cardKind==='dare'?social.pendingTargetId:social.actorId;if(responder!==userId)return`<span class="tag" data-tone="cyan">Waiting for ${escapeHTML(playerName(session,responder))}</span>`;
    if(social.prompt?.options?.length)return`<div class="filter-row">${social.prompt.options.map(option=>button(option,'answer-choice',`data-choice="${escapeHTML(option)}"`)).join('')}</div>${button('Pass / Not for Me','pass')}`;
    if(social.answerState.mode==='TYPE'&&social.answerState.status!=='SUBMITTED')return`${input('ccLiveAnswer','Answer')}${button('Submit Answer','answer-type-submit')}${button('Pass / Not for Me','pass')}`;
    return`${button('Answered Live','answer-live')} ${button('Type Answer','answer-type-open')} ${button('Pass / Not for Me','pass')}`;
  }
  if(step==='PARANOIA_PHASE'&&social.actorId===userId)return`${button('Classic','paranoia-classic')} ${button('Stranger','paranoia-stranger')}`;
  if(step==='PARANOIA_CLASSIC_ANSWER'&&social.pendingTargetId===userId)return targetButtons(session,state.players.filter(p=>p.id!==userId).map(p=>p.id),'paranoia-answer');
  if(step==='PARANOIA_CLASSIC_DECISION'&&social.classicAnswerPlayerId===userId)return`${button('Reveal','paranoia-reveal')} ${button('Keep Secret','paranoia-secret')}`;
  if(step==='PARANOIA_TARGET_ANSWER'&&social.pendingTargetId===userId)return button('Answered Live','paranoia-target-answered');
  if(step==='PARANOIA_VOTE'&&social.paranoiaVote?.eligibleVoterIds.includes(userId)&&!social.paranoiaVote.votes[userId])return`${button('Believe','paranoia-vote','data-vote="BELIEVE"')} ${button('Lying','paranoia-vote','data-vote="LYING"')} ${button('Holding Back','paranoia-vote','data-vote="HOLDING_BACK"')}`;
  if(step==='DUEL_TIMER'&&social.actorId===userId)return`${button('15 sec','duel-timer','data-seconds="15"')} ${button('30 sec','duel-timer','data-seconds="30"')} ${button('45 sec','duel-timer','data-seconds="45"')}`;
  if(step==='DUEL_INITIATOR'&&social.pendingDuel?.initiatorId===userId)return`${textarea('ccDuelResponse','Your Duel response')}${button('Submit Response','duel-response','data-side="initiator"')} ${button('Answered Live','duel-response-live','data-side="initiator"')}`;
  if(step==='DUEL_OPPONENT'&&social.pendingDuel?.opponentId===userId)return`${textarea('ccDuelResponse','Your Duel response')}${button('Submit Response','duel-response','data-side="opponent"')} ${button('Answered Live','duel-response-live','data-side="opponent"')}`;
  if(step==='DUEL_VOTE'&&social.pendingDuel?.vote?.eligibleVoterIds.includes(userId)&&!social.pendingDuel.vote.votes[userId])return targetButtons(session,[social.pendingDuel.initiatorId,social.pendingDuel.opponentId!],'duel-vote');
  if(step==='CHAOS_RESOLVE'&&social.actorId===userId)return`${promptBox('CHAOS',social.chaosEffectId==='BLIND_SWAP'?'Blind Swap — everyone passes up to 3 random cards.':'Reverse Order — direction flips for this Chaos cycle.')}${button('Resolve Chaos','chaos-resolve')}`;
  if(step==='TABOO_QUESTION'&&social.actorId===userId)return`${textarea('ccTabooQuestion','Ask the target one question')}${button('Ask Question','taboo-question-submit')}`;
  if(step==='TABOO_ANSWER'&&social.pendingTargetId===userId)return`${social.question?promptBox('TABOO',social.question):''}${button('YES','taboo-answer','data-answer="YES"')} ${button('Anything Else / Refuse','taboo-answer','data-answer="OTHER"')}`;
  if(step==='GROUP_QUESTION'&&social.actorId===userId)return`${textarea('ccGroupQuestion','Question for everyone')}${input('ccGroupOptionA','Choice A')}${input('ccGroupOptionB','Choice B')}${button('Ask Everyone','group-question-submit')}`;
  if(step==='GROUP_ANSWER'&&social.pendingTargetIds.includes(userId)&&!social.groupAnswers?.[userId])return`<div class="filter-row">${(social.groupOptions??[]).map(choice=>button(choice,'group-answer',`data-choice="${escapeHTML(choice)}"`)).join('')}</div>`;
  if(step==='GROUP_DARE'&&social.actorId===userId)return`${textarea('ccGroupDare','Whole-group dare')}${button('Set Group Dare','group-dare-submit')}`;
  if(step==='GROUP_COMPLETE'&&social.pendingTargetIds.includes(userId)&&!social.groupCompletions?.[userId])return`${social.groupDare?promptBox('GROUP DARE',social.groupDare):''}${button('Done','group-complete','data-completion="DONE"')} ${button('Pass','group-complete','data-completion="PASS"')}`;
  if(step==='MACHIAVELLI_CHOICE'&&social.actorId===userId)return`<div class="filter-row">${MACHIAVELLI.map(([effect,label])=>button(label,'machiavelli',`data-effect="${effect}"`)).join('')}</div>`;
  if(step==='REVERSE_QUESTION'&&social.actorId===userId)return`${textarea('ccReverseQuestion','Ask your target')}${button('Ask Question','reverse-question-submit')}`;
  if(step==='REVERSE_ANSWER'&&social.pendingTargetId===userId)return`${social.question?promptBox('REVERSE CONFESSION',social.question):''}${textarea('ccReverseAnswer','Your answer')}${button('Submit Answer','reverse-answer-submit')} ${button('Answered Live','reverse-answer-live')}`;
  if(step==='DIG_QUESTION'&&social.actorId===userId)return`${textarea('ccDigQuestion','Ask a question about yourself')}${button('Ask Question','dig-question-submit')} ${button('Asked Live','dig-question-live')}`;
  if(step==='DIG_ANSWER'&&social.pendingTargetId===userId)return button('Answered / Complete','dig-complete');
  return'<span class="tag" data-tone="cyan">Waiting for the active player</span>';
}

function renderLiveSession(session:LiveSession,userId:string):void{
  const state=session.state,human=state.players.find(p=>p.id===userId),current=state.players.find(p=>p.id===state.currentPlayerId),top=state.discardPile.at(-1),active=activeStateCopy(session),humanTurn=state.currentPlayerId===userId&&!state.social&&!state.pendingEffect;
  const roomName=document.querySelector<HTMLElement>('#gameRoomName');if(roomName)roomName.textContent=`Room ${session.room.joinCode}`;
  const roomMeta=document.querySelector<HTMLElement>('#gameRoomMeta');if(roomMeta)roomMeta.textContent=`${state.players.length} players • shared live session • rev ${state.revision}`;
  const badge=document.querySelector<HTMLElement>('#modeBadge');if(badge){badge.textContent='LIVE';badge.dataset.tone='lime';}
  const phase=document.querySelector<HTMLElement>('#boardPhaseLabel');if(phase)phase.textContent=state.phase.replaceAll('_',' / ');
  const currentName=document.querySelector<HTMLElement>('#currentTurnName');if(currentName)currentName.textContent=playerName(session,current?.id);
  const activeTitle=document.querySelector<HTMLElement>('#activeChallengeTitle');if(activeTitle)activeTitle.textContent=active.title;
  const activeCopy=document.querySelector<HTMLElement>('#activeChallengeCopy');if(activeCopy)activeCopy.textContent=active.copy;
  const inline=document.querySelector<HTMLElement>('#inlineFlowControls');if(inline)inline.innerHTML=socialControls(session,userId);
  const colorLabel=document.querySelector<HTMLElement>('#activeColorLabel');if(colorLabel)colorLabel.textContent=state.activeColor?state.activeColor.toUpperCase():'—';
  const timer=document.querySelector<HTMLElement>('#timerValue');if(timer)timer.textContent=state.timer?String(Math.max(0,Math.ceil((state.timer.deadlineAt-Date.now())/1000))):'—';
  const list=document.querySelector<HTMLElement>('#playerList');if(list)list.innerHTML=state.players.map(p=>{const view=session.players.find(item=>item.id===p.id);return`<div class="player-row${p.id===state.currentPlayerId?' is-current':''}${p.id===userId?' is-you':''}"><span class="avatar">${escapeHTML((view?.name||'?').slice(0,1).toUpperCase())}</span><span class="player-meta"><b>${escapeHTML(view?.name||p.id)}</b><span>${p.id===userId?'You':'Connected'}</span></span><strong class="card-count">${p.hand.length}</strong></div>`;}).join('');
  const hand=document.querySelector<HTMLElement>('#handScroll');if(hand)hand.innerHTML=human?.hand.map(card=>renderCard(card,true,isLegalPlay(state,userId,card.id))).join('')||'<div class="empty-state"><h3>Empty hand</h3><p>Awaiting authoritative win check.</p></div>';
  const handCount=document.querySelector<HTMLElement>('#handCount');if(handCount)handCount.textContent=`${human?.hand.length??0} cards`;
  const discard=document.querySelector<HTMLElement>('#discardSlot');if(discard)discard.innerHTML=top?renderCard(top,false,false):'<span class="tag">No discard</span>';
  const drawCount=document.querySelector<HTMLElement>('#drawPileCount');if(drawCount)drawCount.textContent=`${state.drawPile.length} left`;
  const drawButton=document.querySelector<HTMLButtonElement>('#drawButton');if(drawButton)drawButton.setAttribute('aria-disabled',String(!humanTurn||(human?.ghostTurnsRemaining??0)>0));
  const social=state.social,affected=social?.cardKind==='dare'?social.pendingTargetId:social?.actorId;
  const pass=document.querySelector<HTMLButtonElement>('[data-action="safety-pass"]');if(pass)pass.setAttribute('aria-disabled',String(!(social&&['truth','dare'].includes(social.cardKind)&&affected===userId)));
  const rewind=document.querySelector<HTMLButtonElement>('[data-action="safety-rewind"]');if(rewind)rewind.setAttribute('aria-disabled',String(!(social?.canonicalStep==='PRIVATE_PREVIEW'&&social.promptSource==='ROULETTE'&&social.actorId===userId&&!state.rewindUsedByPlayerIds.includes(userId))));
  const nope=document.querySelector<HTMLButtonElement>('[data-action="use-nope"]'),nopeCard=human?.hand.find(card=>card.kind==='nope');if(nope)nope.setAttribute('aria-disabled',String(!(nopeCard&&social&&['truth','dare'].includes(social.cardKind)&&affected===userId)));
  const flag=document.querySelector<HTMLButtonElement>('[data-action="safety-flag"]');if(flag)flag.setAttribute('aria-disabled',String(!social?.prompt));
  const revision=document.querySelector<HTMLElement>('#revisionLabel');if(revision)revision.textContent=`Server rev ${state.revision} · Railway live`;showGameView();
}

function extractApiMessage(error:unknown):string{if(error instanceof ApiError){try{const body=JSON.parse(error.message) as{message?:string;error?:string};return body.message||body.error||error.message;}catch{return error.message;}}return error instanceof Error?error.message:'Request failed.';}
function toast(title:string,copy:string):void{const node=document.createElement('div');node.style.cssText='position:fixed;right:18px;bottom:18px;z-index:99999;background:#111827;color:#fff;padding:12px 14px;border-radius:12px;max-width:360px;box-shadow:0 10px 30px #0008';node.innerHTML=`<b>${escapeHTML(title)}</b><div style="margin-top:4px;font-size:12px">${escapeHTML(copy)}</div>`;document.body.append(node);window.setTimeout(()=>node.remove(),3200);}
function readRoomCreatePayload(){const sources:Record<string,boolean>={};document.querySelectorAll<HTMLButtonElement>('[data-source]').forEach(item=>{if(item.dataset.source)sources[item.dataset.source]=item.getAttribute('aria-pressed')!=='false';});return{roomName:(document.querySelector<HTMLInputElement>('#roomName')?.value||'Night Squad').trim(),mode:document.querySelector<HTMLSelectElement>('#modeSelect')?.value||document.querySelector<HTMLElement>('[data-mode][aria-pressed="true"]')?.dataset.mode||'party',playerCount:Number(document.querySelector<HTMLInputElement>('#playerCount')?.value||5),world:(document.querySelector<HTMLSelectElement>('#worldSelect')?.value==='adult'?'adult':'clean') as'adult'|'clean',ceiling:Number(document.querySelector<HTMLSelectElement>('#ceilingSelect')?.value||3),sources};}
function installLiveControls():void{const simulation=document.querySelector<HTMLButtonElement>('#startGameButton');if(!simulation||document.querySelector('[data-action="create-live-game"]'))return;simulation.innerHTML='<svg class="icon"><use href="#i-play" /></svg>Start Simulation';simulation.classList.remove('button--primary');const live=document.createElement('button');live.className='button button--primary';live.type='button';live.dataset.action='create-live-game';live.innerHTML='<svg class="icon"><use href="#i-wifi" /></svg>Create Live Game';simulation.parentElement?.insertBefore(live,simulation);const joinLabel=document.querySelector<HTMLLabelElement>('label[for="joinCode"]');if(joinLabel)joinLabel.textContent='Join live room';const joinInput=document.querySelector<HTMLInputElement>('#joinCode'),helper=joinInput?.parentElement?.querySelector<HTMLElement>('.field-help');if(helper)helper.textContent='Joins the shared Railway room used by both Web and Telegram.';}

export function startWebLiveRooms(api:CribbitApiClient):()=>void{
  let live:LiveSession|null=null,pendingAuthenticatedAction:(()=>void)|null=null;
  const authUnsubscribe=cribbitAuth.subscribe(state=>{if(state.status==='AUTHENTICATED'&&pendingAuthenticatedAction){const action=pendingAuthenticatedAction;pendingAuthenticatedAction=null;action();}});
  const requireAuth=(action:()=>void):void=>{if(cribbitAuth.current.status==='AUTHENTICATED')return action();pendingAuthenticatedAction=action;openWebAuthDialog(api);};
  const openRoom=async(room:RoomSessionResult):Promise<void>=>{const auth=cribbitAuth.current;if(auth.status!=='AUTHENTICATED')return;live?.unsubscribe?.();live?.realtime.disconnect();const snapshot=await api.getSnapshot<GameState>(room.sessionId),realtime=new CribbitRealtimeClient(api.config);live={room,state:snapshot.state,players:snapshot.players,realtime};const socket=realtime.connect();const refresh=async(payload:{sessionId?:string})=>{if(!live||payload.sessionId!==live.room.sessionId)return;try{const next=await api.getSnapshot<GameState>(live.room.sessionId);live.state=next.state;live.players=next.players;renderLiveSession(live,auth.user.id);}catch(error){console.warn('[Cribbit] Web live snapshot refresh failed.',error);}};socket.on('session-updated',refresh);realtime.joinSession(room.sessionId);live.unsubscribe=()=>socket.off('session-updated',refresh);renderLiveSession(live,auth.user.id);toast('Live room connected',`Room code ${room.joinCode}. Web and Telegram players share this session.`);};
  const send=async(body:CommandBody):Promise<void>=>{const auth=cribbitAuth.current;if(!live||auth.status!=='AUTHENTICATED')return;const command={...body,commandId:crypto.randomUUID(),playerId:auth.user.id,expectedRevision:live.state.revision,sessionId:live.room.sessionId} as GameCommand;try{const response=await api.sendCommand<GameState>(command);if(response.state)live.state=response.state;else live.state=(await api.getSnapshot<GameState>(live.room.sessionId)).state;renderLiveSession(live,auth.user.id);if(!response.ok)toast('Action rejected',response.error?.message||'The shared game rejected that action.');}catch(error){toast('Live action failed',extractApiMessage(error));try{const snapshot=await api.getSnapshot<GameState>(live.room.sessionId);live.state=snapshot.state;live.players=snapshot.players;renderLiveSession(live,auth.user.id);}catch{/* preserve last known state */}}};
  const createLive=():void=>requireAuth(()=>{void api.createRoom(readRoomCreatePayload()).then(openRoom).catch(error=>toast('Could not create live game',extractApiMessage(error)));});
  const joinLive=():void=>requireAuth(()=>{const code=(document.querySelector<HTMLInputElement>('#joinCode')?.value||'').trim().toUpperCase();if(!/^[A-Z0-9]{4,12}$/.test(code))return toast('Invalid room code','Enter 4–12 letters or numbers.');void api.joinRoom(code).then(openRoom).catch(error=>toast('Could not join room',extractApiMessage(error)));});
  installLiveControls();

  const capture=(event:Event):void=>{const target=event.target instanceof Element?event.target:null;if(!target)return;const create=target.closest('[data-action="create-live-game"]'),join=target.closest('[data-action="join-room"]');if(create||join){event.preventDefault();event.stopImmediatePropagation();if(create)createLive();else joinLive();return;}if(!live)return;
    const play=target.closest<HTMLElement>('[data-action="play-card"]'),draw=target.closest('[data-action="draw-card"]'),pass=target.closest('[data-action="safety-pass"]'),rewind=target.closest('[data-action="safety-rewind"]'),nope=target.closest('[data-action="use-nope"]'),flag=target.closest('[data-action="safety-flag"]'),liveAction=target.closest<HTMLElement>('[data-live-action]');if(!(play||draw||pass||rewind||nope||flag||liveAction))return;event.preventDefault();event.stopImmediatePropagation();
    if(play?.dataset.cardId)return void send({type:'PLAY_CARD',cardId:play.dataset.cardId});if(draw)return void send({type:'DRAW_CARD'});if(pass)return void send({type:'PASS_PROMPT'});if(rewind)return void send({type:'REWIND_PROMPT'});if(flag)return void send({type:'FLAG_PROMPT',promptId:live.state.social?.prompt?.id||'',reasonCode:'USER_FLAG'});if(nope){const auth=cribbitAuth.current,userId=auth.status==='AUTHENTICATED'?auth.user.id:'',cardId=live.state.players.find(p=>p.id===userId)?.hand.find(card=>card.kind==='nope')?.id;if(cardId)return void send({type:'PLAY_NOPE',cardId});return;}if(!liveAction)return;
    const action=liveAction.dataset.liveAction;
    if(action==='wild-color')return void send({type:'SELECT_WILD_COLOR',color:liveAction.dataset.color as CardColor});
    if(action==='ghost-activate')return void send({type:'ACTIVATE_GHOST'});if(action==='ghost-end')return void send({type:'END_GHOST_TURN'});
    if(action==='prompt-manual')return void send({type:'SELECT_PROMPT_SOURCE',source:'MANUAL'});if(action==='prompt-roulette')return void send({type:'SELECT_PROMPT_SOURCE',source:'ROULETTE'});if(action==='manual-submit'){const text=document.querySelector<HTMLTextAreaElement>('#ccManualPrompt')?.value.trim()||'';if(!text)return toast('Prompt required','Write your prompt first.');return void send({type:'SUBMIT_MANUAL_PROMPT',text});}if(action==='prompt-publish')return void send({type:'PUBLISH_PROMPT'});
    if(action==='dare-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_DARE_TARGET',targetId:liveAction.dataset.playerId});
    if(action==='answer-live')return void send({type:'MARK_ANSWERED_LIVE'});if(action==='answer-type-open')return void send({type:'SELECT_ANSWER_MODE',mode:'TYPE'});if(action==='answer-type-submit'){const value=document.querySelector<HTMLInputElement>('#ccLiveAnswer')?.value.trim()||'';if(!value)return toast('Answer required','Type an answer first.');void(async()=>{await send({type:'REVIEW_ANSWER',value});await send({type:'SUBMIT_ANSWER'});})();return;}if(action==='answer-choice'&&liveAction.dataset.choice)return void send({type:'SUBMIT_CHOICE',choice:liveAction.dataset.choice});if(action==='pass')return void send({type:'PASS_PROMPT'});
    if(action==='paranoia-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_PARANOIA_TARGET',targetId:liveAction.dataset.playerId});if(action==='paranoia-classic')return void send({type:'SELECT_PARANOIA_PHASE',phase:'CLASSIC'});if(action==='paranoia-stranger')return void send({type:'SELECT_PARANOIA_PHASE',phase:'STRANGER'});if(action==='paranoia-answer'&&liveAction.dataset.playerId)return void send({type:'SELECT_PARANOIA_CLASSIC_ANSWER',targetId:liveAction.dataset.playerId});if(action==='paranoia-reveal')return void send({type:'SUBMIT_PARANOIA_CLASSIC_DECISION',decision:'REVEAL'});if(action==='paranoia-secret')return void send({type:'SUBMIT_PARANOIA_CLASSIC_DECISION',decision:'KEEP_SECRET'});if(action==='paranoia-target-answered')return void send({type:'MARK_ANSWERED_LIVE'});if(action==='paranoia-vote'&&liveAction.dataset.vote)return void send({type:'SUBMIT_PARANOIA_VOTE',vote:liveAction.dataset.vote as'BELIEVE'|'LYING'|'HOLDING_BACK'});
    if(action==='duel-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_DUEL_TARGET',targetId:liveAction.dataset.playerId});if(action==='duel-timer')return void send({type:'SELECT_DUEL_TIMER',seconds:Number(liveAction.dataset.seconds) as 15|30|45});if(action==='duel-response'){const value=document.querySelector<HTMLTextAreaElement>('#ccDuelResponse')?.value.trim()||'';if(!value)return toast('Response required','Write your Duel response.');return void send({type:'SUBMIT_DUEL_RESPONSE',side:liveAction.dataset.side as'initiator'|'opponent',value});}if(action==='duel-response-live')return void send({type:'SUBMIT_DUEL_RESPONSE',side:liveAction.dataset.side as'initiator'|'opponent',completionOnly:true});if(action==='duel-vote'&&liveAction.dataset.playerId)return void send({type:'DUEL_VOTE',winnerId:liveAction.dataset.playerId});
    if(action==='chaos-resolve')return void send({type:'RESOLVE_CHAOS'});if(action==='tag-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_TAG_TARGET',targetId:liveAction.dataset.playerId});if(action==='hijack-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_HIJACK_TARGET',targetId:liveAction.dataset.playerId});
    if(action==='taboo-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_TABOO_TARGET',targetId:liveAction.dataset.playerId});if(action==='taboo-question-submit'){const text=document.querySelector<HTMLTextAreaElement>('#ccTabooQuestion')?.value.trim()||'';if(!text)return toast('Question required','Ask the Taboo target a question.');return void send({type:'SUBMIT_TABOO_QUESTION',text});}if(action==='taboo-answer')return void send({type:'SUBMIT_TABOO_ANSWER',answer:liveAction.dataset.answer as'YES'|'OTHER'});
    if(action==='group-question-submit'){const text=document.querySelector<HTMLTextAreaElement>('#ccGroupQuestion')?.value.trim()||'',a=document.querySelector<HTMLInputElement>('#ccGroupOptionA')?.value.trim()||'',b=document.querySelector<HTMLInputElement>('#ccGroupOptionB')?.value.trim()||'';if(!text||!a||!b)return toast('Question and choices required','Provide the question and two choices.');return void send({type:'SUBMIT_GROUP_QUESTION',text,options:[a,b]});}if(action==='group-answer'&&liveAction.dataset.choice)return void send({type:'SUBMIT_GROUP_ANSWER',choice:liveAction.dataset.choice});if(action==='group-dare-submit'){const text=document.querySelector<HTMLTextAreaElement>('#ccGroupDare')?.value.trim()||'';if(!text)return toast('Dare required','Write the group Dare.');return void send({type:'SUBMIT_GROUP_DARE',text});}if(action==='group-complete')return void send({type:'COMPLETE_GROUP_DARE',completion:liveAction.dataset.completion as'DONE'|'PASS'});
    if(action==='machiavelli')return void send({type:'SELECT_MACHIAVELLI_EFFECT',effect:liveAction.dataset.effect as MachiavelliEffectId});
    if(action==='reverse-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_REVERSE_CONFESSION_TARGET',targetId:liveAction.dataset.playerId});if(action==='reverse-question-submit'){const text=document.querySelector<HTMLTextAreaElement>('#ccReverseQuestion')?.value.trim()||'';if(!text)return toast('Question required','Ask your target a question.');return void send({type:'SUBMIT_REVERSE_CONFESSION_QUESTION',text});}if(action==='reverse-answer-submit'){const value=document.querySelector<HTMLTextAreaElement>('#ccReverseAnswer')?.value.trim()||'';if(!value)return toast('Answer required','Type an answer first.');return void send({type:'SUBMIT_REVERSE_CONFESSION_ANSWER',value});}if(action==='reverse-answer-live')return void send({type:'SUBMIT_REVERSE_CONFESSION_ANSWER',answeredLive:true});
    if(action==='dig-target'&&liveAction.dataset.playerId)return void send({type:'SELECT_DIG_ME_TARGET',targetId:liveAction.dataset.playerId});if(action==='dig-question-submit'){const text=document.querySelector<HTMLTextAreaElement>('#ccDigQuestion')?.value.trim()||'';if(!text)return toast('Question required','Ask a question about yourself.');return void send({type:'SUBMIT_DIG_ME_QUESTION',text});}if(action==='dig-question-live')return void send({type:'SUBMIT_DIG_ME_QUESTION',askedLive:true});if(action==='dig-complete')return void send({type:'COMPLETE_DIG_ME'});
  };
  document.addEventListener('click',capture,true);
  const enterCapture=(event:KeyboardEvent):void=>{if(event.key!=='Enter'||!(event.target instanceof HTMLInputElement)||event.target.id!=='joinCode')return;event.preventDefault();event.stopImmediatePropagation();joinLive();};document.addEventListener('keydown',enterCapture,true);
  return()=>{authUnsubscribe();live?.unsubscribe?.();live?.realtime.disconnect();document.removeEventListener('click',capture,true);document.removeEventListener('keydown',enterCapture,true);};
}
